# Generated by Django 2.1.7 on 2020-11-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meishi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('food_name', models.CharField(max_length=30)),
                ('food_author', models.CharField(max_length=8)),
                ('food_money', models.FloatField()),
                ('food_star', models.CharField(default='普通', max_length=10)),
            ],
        ),
    ]
